### ISSUE TITLE
Construcción de la ventana1 primera parte

### ISSUE THREAD

**Issue by alejandroBs2323** [alejandroBs2323/Clase9#1]
construir la ventana Ventana1() y hacer el formulario para ingresar la información del cliente

**Comment by Manuelajurado** [comment]
Saludos, voy a encargarme de esta funcionalidad.

**Comment by alejandroBs2323** [comment]
Listo, trabajo cumplido, por favor revisar el nuevo issue para hacer en ventana1.py el formulario de registro del usuario

**Comment by alejandroBs2323** [comment]
Listo trabajo cumplido, por favor revisar el nuevo issue para hacer en ventana1.py e formulario de registro del usuario
