### ISSUE TITLE
Programar el botón para buscar las preguntas de recuperación de contraseña

### ISSUE THREAD

**Issue by alejandroBs2323** [alejandroBs2323/Clase9#6]
validar que se ingrese el documento del usuario al cual se le va a buscar la contraseña 
Validar que el documento sea un dato tipo numérico
Crear la clase usuario con sus 11 propiedades 
Solo considerar un pasword
Buscar las preguntas para recuperar la contraseña

**Comment by Manuelajurado** [comment]
Me voy a encargar de este issue, voy a desarrollarlo
Pendiente de alguna sugerencia

**Comment by alejandroBs2323** [comment]
Listo quedo pendiente de su primer push y pull request

**Comment by alejandroBs2323** [comment]
se cierra este issue #6
